#!/bin/bash -e

DOCKER_REPO=${DOCKER_REPO}
NAMESPACE=${NAMESPACE:-mayahiro}
GRPC_VERSION=${GRPC_VERSION:-1.19}
GRPC_WEB_VERSION=${GRPC_WEB_VERSION:-1.2.1}
GO_VERSION=${GO_VERSION:-1.15}
BUILD_VERSION=${BUILD_VERSION:-1}
CONTAINER=${DOCKER_REPO}${NAMESPACE}
LATEST=${1:false}
BUILDS=("protoc-all" "protoc" "prototool" "grpc-cli" "gen-grpc-gateway")
